// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArHvC80Pha5uHAJWgTFmKdpA0ALg50xkI',
    appId: '1:320332578533:web:24a3a56035849598525e0c',
    messagingSenderId: '320332578533',
    projectId: 'study-1084a',
    authDomain: 'study-1084a.firebaseapp.com',
    databaseURL: 'https://study-1084a-default-rtdb.firebaseio.com',
    storageBucket: 'study-1084a.firebasestorage.app',
    measurementId: 'G-H74C38S5VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVbgdTtVa1JGgGruze5WPHBUWkc0p0lqg',
    appId: '1:320332578533:android:4dc6badc9ebd7485525e0c',
    messagingSenderId: '320332578533',
    projectId: 'study-1084a',
    databaseURL: 'https://study-1084a-default-rtdb.firebaseio.com',
    storageBucket: 'study-1084a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhbQ6gslinCa7WWFsfcvE8Edsm9tTeiFM',
    appId: '1:320332578533:ios:305b7ae0c3436ee2525e0c',
    messagingSenderId: '320332578533',
    projectId: 'study-1084a',
    databaseURL: 'https://study-1084a-default-rtdb.firebaseio.com',
    storageBucket: 'study-1084a.firebasestorage.app',
    iosBundleId: 'com.example.learningmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhbQ6gslinCa7WWFsfcvE8Edsm9tTeiFM',
    appId: '1:320332578533:ios:305b7ae0c3436ee2525e0c',
    messagingSenderId: '320332578533',
    projectId: 'study-1084a',
    databaseURL: 'https://study-1084a-default-rtdb.firebaseio.com',
    storageBucket: 'study-1084a.firebasestorage.app',
    iosBundleId: 'com.example.learningmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArHvC80Pha5uHAJWgTFmKdpA0ALg50xkI',
    appId: '1:320332578533:web:6d529c7317a4f257525e0c',
    messagingSenderId: '320332578533',
    projectId: 'study-1084a',
    authDomain: 'study-1084a.firebaseapp.com',
    databaseURL: 'https://study-1084a-default-rtdb.firebaseio.com',
    storageBucket: 'study-1084a.firebasestorage.app',
    measurementId: 'G-DN6GC3YXW9',
  );
}
